fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user:
  resource: "@AppBundle/Resources/config/routing/user.yml"
  prefix: /users

app:
  resource: "@AppBundle/Controller/"
  type: annotation
